# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('show_on_site', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('priority', models.IntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('show_on_site', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('main_image', models.ImageField(blank=True, upload_to='')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('overview', tinymce.models.HTMLField(blank=True, null=True)),
                ('features', tinymce.models.HTMLField(blank=True, null=True)),
                ('technical_features', tinymce.models.HTMLField(blank=True, null=True)),
                ('benefits', tinymce.models.HTMLField(blank=True, null=True)),
                ('priority', models.IntegerField(default=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('show_on_site', models.BooleanField(default=True)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
