# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=tinymce.models.HTMLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=tinymce.models.HTMLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='overview',
            field=tinymce.models.HTMLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_features',
            field=tinymce.models.HTMLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
