# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170821_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brochure',
            field=models.FileField(blank=True, upload_to='uploads/pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
