# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_brochure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Preferrable size 510x460', upload_to='uploads/products'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='uploads/products'),
        ),
    ]
