# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('show_on_site', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('brochure', models.FileField(blank=True, upload_to=b'uploads/pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[b'pdf'])])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
