# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_sitetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('show_on_site', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to=b'uploads/profile')),
                ('author_name', models.CharField(max_length=50)),
                ('author_title', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
