# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:38
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
