# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='buyer_facility',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('dia_center', 'Diagnostic Center'), ('others', 'Others')], default='others', help_text='Facility', max_length=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('parts', 'Parts'), ('services', 'Services'), ('contact', 'Contact'), ('others', 'Others')], db_index=True, default='others', max_length=10),
        ),
    ]
