# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_auto_20170825_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='seller_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('eqd', 'Equipment Dealer'), ('fin_ins', 'Financial Institution'), ('ser_com', 'Service Company'), ('OEM', 'OEM'), ('part_supp', 'Parts Supplier'), ('others', 'Others')], default='others', help_text='Which of these best describes you?', max_length=20),
        ),
    ]
